export { default as Auth } from './Auth/Auth'
export { default as Calendar } from './Calendar/Calendar'
export { default as Content } from './Content/Content'
export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as Layout } from './Layout/Layout'
export { default as ControlModal } from './Modal/ControlModal'
export { default as Block } from './UI/Block/Block'
